//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingsDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DomainModel;
    
    public partial class PurchasesEntities : DbContext
    {
        public PurchasesEntities()
            : base("name=PurchasesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MonthlyBill> MonthlyBills { get; set; }
        public virtual DbSet<PayedBillsMonth> PayedBillsMonths { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
    }
}
